Repository bptlab/TracEX, pull requests merged in 2024-04, with the labels that each got.

#74 Enhancement/70 implement few shot pipeline
  .idea/.gitignore
  tracex/db.sqlite3
  tracex/extraction/content/outputs/all_traces.csv
  tracex/extraction/content/outputs/single_trace.csv
  tracex/extraction/content/outputs/single_trace_event_type.xes
  tracex/extraction/logic/module.py
  tracex/extraction/logic/modules/module_activity_labeler.py
  tracex/extraction/logic/modules/module_cohort_tagger.py
  tracex/extraction/logic/modules/module_event_log_comparator.py
  tracex/extraction/logic/modules/module_event_type_classifier.py
  tracex/extraction/logic/modules/module_location_extractor.py
  tracex/extraction/logic/modules/module_metrics_analyzer.py
  tracex/extraction/logic/modules/module_patient_journey_preprocessor.py
  tracex/extraction/logic/modules/module_time_extractor.py
  tracex/extraction/logic/modules/module_time_extractor_backup.py
  tracex/extraction/logic/orchestrator.py
  tracex/extraction/logic/prompts.py
  tracex/tracex/logic/logger.py
  tracex/tracex/logic/utils.py
Labels: enhancement, User Story

#102 Refactoring: Fixing the df warnings to be able to use Pandas 3.0 in the future
  tracex_project/extraction/logic/modules/module_time_extractor.py
Labels: improvement

#108 Feature/82 loading prompts db
  tracex_project/db.sqlite3
  tracex_project/extraction/logic/modules/module_activity_labeler.py
  tracex_project/extraction/logic/modules/module_cohort_tagger.py
  tracex_project/extraction/logic/modules/module_event_type_classifier.py
  tracex_project/extraction/logic/modules/module_location_extractor.py
  tracex_project/extraction/logic/modules/module_metrics_analyzer.py
  tracex_project/extraction/logic/modules/module_patient_journey_preprocessor.py
  tracex_project/extraction/logic/modules/module_time_extractor.py
  tracex_project/extraction/logic/prompts.py
  tracex_project/extraction/migrations/0018_prompt_category.py
  tracex_project/extraction/models.py
  tracex_project/patient_journey_generator/generator.py
  tracex_project/patient_journey_generator/prompts.py
  tracex_project/trace_comparator/comparator.py
  tracex_project/trace_comparator/prompts.py
Labels: High Prio, feature
